name: build-push-quay
on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile*'

  workflow_dispatch:

jobs:

  docker_matrix:

    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.GIT-COMMITS }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Dockerfile names from commits
        id: set-matrix
        run: |
          echo -n ::set-output name=GIT-COMMITS::
          COMMITS=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }} **/Dockerfile* | jq -R '[.]' | jq -s -c 'add')
          echo "${COMMITS}"

      - name: Get Dockerfiles  
        uses: jitterbit/get-changed-files@v1
        id: set-matrix-jitter
        with:
          format: json

      - name: Check json jitterbit
        run: |
          echo "${{ steps.set-matrix-jitter.outputs.all }}"

      - name: Check json new
        run: |
          echo "${{ steps.set-matrix.outputs.GIT-COMMITS }}"

  build:

    needs: docker_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.docker_matrix.outputs.matrix) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Get image name
        id: image_name
        run: |
          echo -n ::set-output name=IMAGE_NAME::
          NAME=$(echo ${{ matrix.dockerfile }} | awk -F '[.-]' '{print $2}')
          echo "${NAME}"

      - name: Get image tags
        id: image_tags
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          TAGS=$(echo ${{ matrix.dockerfile }} | awk -F '[-]' '{print $2}')
          TAGS+=('latest')
          ( IFS=$','; echo "${TAGS[*]}" )
