name: build-push-quay
on:
  push:
    branches:
      - main
    paths:
      - **/Dockerfile*
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
 
      - name: Get Dockerfiles
      - uses: jitterbit/get-changed-files@v1
        id: Dockerfiles
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Get image name
        id: image_name
        run: |
          echo -n ::set-output name=IMAGE_NAME::
          NAME=$(echo ${{ steps.Dockerfiles.outputs.all }} | awk -F '[.-]' '{print $2}')
          echo "${NAME}"
 
      - name: Get image tags
        id: image_tags
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          TAGS=$(echo ${{ steps.Dockerfiles.outputs.all }} | awk -F '[-]' '{print $2}')
          TAGS+=('latest')
          ( IFS=$','; echo "${TAGS[*]}" )        
          
      - name: Build and publish image to Quay
        uses: docker/build-push-action@v1
        with:
          path: ${{ steps.image_name.outputs.IMAGE_NAME }}
          dockerfile: ${{ steps.Dockerfiles.outputs.all }}
          registry: ${{ secrets.REGISTRY_SERVER }}
          repository: ${{ secrets.REGISTRY_NAMESPACE }}/${{ steps.image_name.outputs.IMAGE_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tags: "${{ steps.image_tags.outputs.IMAGE_TAGS }}"
          
      - name: Test image
        run: |
          TAG=$(echo ${{ steps.Dockerfiles.outputs.all }} | awk -F '[-]' '{print $2}')
          echo "Running: docker run ${{ steps.image_name.outputs.IMAGE_NAME }}:${TAG}"
          docker run ${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_NAMESPACE }}/${( steps.image_name.outputs.IMAGE_NAME )}:${TAG}
